import { UserAccount } from "./user";
import * as viteUtils from "./utils";
import * as compiler from "./compiler";
import * as config from "./config";
import * as vnode from "./node";
export declare function startLocalNetwork(cfg: any): Promise<vnode.Node>;
export declare function newProvider(url: string): any;
export declare function newAccount(mnemonics: string, index: number, provider: any): UserAccount;
export declare function mint(provider: any): Promise<void>;
export declare function getSnapshotHeight(provider: any): Promise<any>;
export declare function getAccountHeight(provider: any, to: string): Promise<Number>;
export declare function getQuota(provider: any, to: string): Promise<any>;
export declare function getAccountBlock(provider: any, hash?: string): Promise<any>;
export declare function getBalance(provider: any, address: string, tokenId?: string): Promise<any>;
export declare function isReceived(provider: any, hash?: string): Promise<boolean>;
export declare function isConfirmed(provider: any, hash?: string): Promise<boolean>;
export declare const loadViteConfig: typeof config.loadViteConfig;
export declare const compile: typeof compiler.compile;
export declare const compileLegacy: (source: string) => Promise<any>;
export declare const utils: typeof viteUtils;
//# sourceMappingURL=vite.d.ts.map